//MODELS DOG
    // minHeight: {
    //     type: DataTypes.STRING,
    //     allowNull: false
    //   },
    //   maxHeight: {
    //     type: DataTypes.STRING,
    //     allowNull: false
    //   },
    //   minWeight: {
    //     type: DataTypes.STRING,
    //     allowNull: false
    //   },
    //   maxWeight: {
    //     type: DataTypes.STRING,
    //     allowNull: false
    //   },

    //POST DOG

    // minHeight,
    //   maxHeight,
    //   minWeight,
    //   maxWeight,